
var Immolate = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Immolate) {
  Immolate = Immolate || {};


var d;d||(d=typeof Immolate !== 'undefined' ? Immolate : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});var q={},v;for(v in d)d.hasOwnProperty(v)&&(q[v]=d[v]);function ca(a,b){throw b;}var w="",da;w=self.location.href;_scriptDir&&(w=_scriptDir);0!==w.indexOf("blob:")?w=w.substr(0,w.lastIndexOf("/")+1):w="";da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var x=d.printErr||console.warn.bind(console);
for(v in q)q.hasOwnProperty(v)&&(d[v]=q[v]);q=null;d.quit&&(ca=d.quit);var y;d.wasmBinary&&(y=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);"object"!==typeof WebAssembly&&z("no native wasm support detected");var A,ea=new WebAssembly.Table({initial:232,maximum:232,element:"anyfunc"}),fa=!1,ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ja(a,b,c){var e=B;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(b>=c)break;e[b++]=g}else{if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}}var ka="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function la(a,b){var c=a>>1;for(var e=c+b/2;!(c>=e)&&ma[c];)++c;c<<=1;if(32<c-a&&ka)return ka.decode(B.subarray(a,c));c=0;for(e="";;){var f=C[a+2*c>>1];if(0==f||c==b/2)return e;++c;e+=String.fromCharCode(f)}}function na(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)C[b>>1]=a.charCodeAt(f),b+=2;C[b>>1]=0;return b-e}function oa(a){return 2*a.length}
function pa(a,b){for(var c=0,e="";!(c>=b/4);){var f=D[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e}function qa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}D[b>>2]=g;b+=4;if(b+4>c)break}D[b>>2]=0;return b-e}
function ra(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b}var sa,ta,B,C,ma,D,E,ua,va,wa=d.INITIAL_MEMORY||16777216;d.wasmMemory?A=d.wasmMemory:A=new WebAssembly.Memory({initial:wa/65536,maximum:wa/65536});A&&(sa=A.buffer);wa=sa.byteLength;var F=sa;sa=F;d.HEAP8=ta=new Int8Array(F);d.HEAP16=C=new Int16Array(F);d.HEAP32=D=new Int32Array(F);d.HEAPU8=B=new Uint8Array(F);d.HEAPU16=ma=new Uint16Array(F);d.HEAPU32=E=new Uint32Array(F);d.HEAPF32=ua=new Float32Array(F);
d.HEAPF64=va=new Float64Array(F);D[3120]=5255520;function xa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.ua;"number"===typeof c?void 0===b.ma?d.dynCall_v(c):d.dynCall_vi(c,b.ma):c(void 0===b.ma?null:b.ma)}}}var ya=[],za=[],Aa=[],Ba=[];function Ca(){var a=d.preRun.shift();ya.unshift(a)}var G=0,Da=null,Ea=null;d.preloadedImages={};d.preloadedAudios={};
function z(a){if(d.onAbort)d.onAbort(a);x(a);fa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Fa(){var a=H;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var H="immolate.wasm";if(!Fa()){var Ga=H;H=d.locateFile?d.locateFile(Ga,w):w+Ga}
function Ha(){try{if(y)return new Uint8Array(y);if(da)return da(H);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}function Ia(){return y||"function"!==typeof fetch?new Promise(function(a){a(Ha())}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Ha()})}za.push({ua:function(){Ja()}});function Ka(){return 0<Ka.pa}
function La(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ma=void 0;function I(a){for(var b="";B[a];)b+=Ma[B[a++]];return b}var K={},L={},Na={};function Oa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Pa(a,b){a=Oa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Qa(a){var b=Error,c=Pa(a,function(e){this.name=a;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var M=void 0;function Q(a){throw new M(a);}var Ra=void 0;function Sa(a){throw new Ra(a);}function R(a,b,c){function e(h){h=c(h);h.length!==a.length&&Sa("Mismatched type converter count");for(var m=0;m<a.length;++m)S(a[m],h[m])}a.forEach(function(h){Na[h]=b});var f=Array(b.length),g=[],n=0;b.forEach(function(h,m){L.hasOwnProperty(h)?f[m]=L[h]:(g.push(h),K.hasOwnProperty(h)||(K[h]=[]),K[h].push(function(){f[m]=L[h];++n;n===g.length&&e(f)}))});0===g.length&&e(f)}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||Q('type "'+e+'" must have a positive integer typeid pointer');if(L.hasOwnProperty(a)){if(c.xa)return;Q("Cannot register type '"+e+"' twice")}L[a]=b;delete Na[a];K.hasOwnProperty(a)&&(b=K[a],delete K[a],b.forEach(function(f){f()}))}function Ta(a){return{count:a.count,ga:a.ga,ha:a.ha,X:a.X,Y:a.Y,$:a.$,aa:a.aa}}
function Ua(a){Q(a.V.Y.W.name+" instance already deleted")}var Va=!1;function Wa(){}function Xa(a){--a.count.value;0===a.count.value&&(a.$?a.aa.fa(a.$):a.Y.W.fa(a.X))}function Ya(a){if("undefined"===typeof FinalizationGroup)return Ya=function(b){return b},a;Va=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.X?Xa(c):console.warn("object already deleted: "+c.X)});Ya=function(b){Va.register(b,b.V,b.V);return b};Wa=function(b){Va.unregister(b.V)};return Ya(a)}
var Za=void 0,$a=[];function ab(){for(;$a.length;){var a=$a.pop();a.V.ga=!1;a["delete"]()}}function T(){}var bb={};function cb(a,b,c){if(void 0===a[b].Z){var e=a[b];a[b]=function(){a[b].Z.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Z+")!");return a[b].Z[arguments.length].apply(this,arguments)};a[b].Z=[];a[b].Z[e.ja]=e}}
function db(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].Z&&void 0!==d[a].Z[c])&&Q("Cannot register public name '"+a+"' twice"),cb(d,a,a),d.hasOwnProperty(c)&&Q("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].Z[c]=b):(d[a]=b,void 0!==c&&(d[a].Ea=c))}function eb(a,b,c,e,f,g,n,h){this.name=a;this.constructor=b;this.da=c;this.fa=e;this.ba=f;this.va=g;this.ia=n;this.ta=h;this.za=[]}
function fb(a,b,c){for(;b!==c;)b.ia||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ia(a),b=b.ba;return a}function gb(a,b){if(null===b)return this.na&&Q("null is not a valid "+this.name),0;b.V||Q('Cannot pass "'+U(b)+'" as a '+this.name);b.V.X||Q("Cannot pass deleted object as a pointer of type "+this.name);return fb(b.V.X,b.V.Y.W,this.W)}
function hb(a,b){if(null===b){this.na&&Q("null is not a valid "+this.name);if(this.la){var c=this.Aa();null!==a&&a.push(this.fa,c);return c}return 0}b.V||Q('Cannot pass "'+U(b)+'" as a '+this.name);b.V.X||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.ka&&b.V.Y.ka&&Q("Cannot convert argument of type "+(b.V.aa?b.V.aa.name:b.V.Y.name)+" to parameter type "+this.name);c=fb(b.V.X,b.V.Y.W,this.W);if(this.la)switch(void 0===b.V.$&&Q("Passing raw pointer to smart pointer is illegal"),
this.Ca){case 0:b.V.aa===this?c=b.V.$:Q("Cannot convert argument of type "+(b.V.aa?b.V.aa.name:b.V.Y.name)+" to parameter type "+this.name);break;case 1:c=b.V.$;break;case 2:if(b.V.aa===this)c=b.V.$;else{var e=b.clone();c=this.Ba(c,ib(function(){e["delete"]()}));null!==a&&a.push(this.fa,c)}break;default:Q("Unsupporting sharing policy")}return c}
function jb(a,b){if(null===b)return this.na&&Q("null is not a valid "+this.name),0;b.V||Q('Cannot pass "'+U(b)+'" as a '+this.name);b.V.X||Q("Cannot pass deleted object as a pointer of type "+this.name);b.V.Y.ka&&Q("Cannot convert argument of type "+b.V.Y.name+" to parameter type "+this.name);return fb(b.V.X,b.V.Y.W,this.W)}function kb(a){return this.fromWireType(E[a>>2])}function lb(a,b,c){if(b===c)return a;if(void 0===c.ba)return null;a=lb(a,b,c.ba);return null===a?null:c.ta(a)}var mb={};
function ob(a,b){for(void 0===b&&Q("ptr should not be undefined");a.ba;)b=a.ia(b),a=a.ba;return mb[b]}function pb(a,b){b.Y&&b.X||Sa("makeClassHandle requires ptr and ptrType");!!b.aa!==!!b.$&&Sa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Ya(Object.create(a,{V:{value:b}}))}
function V(a,b,c,e){this.name=a;this.W=b;this.na=c;this.ka=e;this.la=!1;this.fa=this.Ba=this.Aa=this.ra=this.Ca=this.ya=void 0;void 0!==b.ba?this.toWireType=hb:(this.toWireType=e?gb:jb,this.ca=null)}function qb(a,b,c){d.hasOwnProperty(a)||Sa("Replacing nonexistant public symbol");void 0!==d[a].Z&&void 0!==c?d[a].Z[c]=b:(d[a]=b,d[a].ja=c)}
function W(a,b){a=I(a);var c=d["dynCall_"+a];for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var rb=void 0;function sb(a){a=tb(a);var b=I(a);X(a);return b}
function Y(a,b){function c(g){f[g]||L[g]||(Na[g]?Na[g].forEach(c):(e.push(g),f[g]=!0))}var e=[],f={};b.forEach(c);throw new rb(a+": "+e.map(sb).join([", "]));}function ub(a,b){for(var c=[],e=0;e<a;e++)c.push(D[(b>>2)+e]);return c}function vb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function wb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Pa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function xb(a,b,c,e,f){var g=b.length;2>g&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var n=null!==b[1]&&null!==c,h=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ca){h=!0;break}var m="void"!==b[0].name,k="",l="";for(c=0;c<g-2;++c)k+=(0!==c?", ":"")+"arg"+c,l+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Oa(a)+"("+k+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";h&&(a+="var destructors = [];\n");var p=h?"destructors":"null";k="throwBindingError invoker fn runDestructors retType classParam".split(" ");e=[Q,e,f,vb,b[0],b[1]];n&&(a+="var thisWired = classParam.toWireType("+p+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+p+", arg"+c+"); // "+b[c+2].name+"\n",k.push("argType"+c),e.push(b[c+2]);n&&(l="thisWired"+(0<l.length?", ":"")+l);a+=(m?"var rv = ":"")+"invoker(fn"+(0<l.length?", ":"")+l+");\n";if(h)a+=
"runDestructors(destructors);\n";else for(c=n?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ca&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",k.push(g+"_dtor"),e.push(b[c].ca));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");k.push(a+"}\n");return wb(k).apply(null,e)}
function yb(a,b,c){a instanceof Object||Q(c+' with invalid "this": '+a);a instanceof b.W.constructor||Q(c+' incompatible with "this" of type '+a.constructor.name);a.V.X||Q("cannot call emscripten binding method "+c+" on deleted object");return fb(a.V.X,a.V.Y.W,b.W)}var zb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ab(a){4<a&&0===--Z[a].oa&&(Z[a]=void 0,zb.push(a))}
function ib(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=zb.length?zb.pop():Z.length;Z[b]={oa:1,value:a};return b}}function U(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Bb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ua[c>>2])};case 3:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Cb(a,b,c){switch(b){case 0:return c?function(e){return ta[e]}:function(e){return B[e]};case 1:return c?function(e){return C[e>>1]}:function(e){return ma[e>>1]};case 2:return c?function(e){return D[e>>2]}:function(e){return E[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Db=Array(256),Eb=0;256>Eb;++Eb)Db[Eb]=String.fromCharCode(Eb);Ma=Db;M=d.BindingError=Qa("BindingError");Ra=d.InternalError=Qa("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.V.Y.W,c=this.V.X,e=a.V.Y.W;for(a=a.V.X;b.ba;)c=b.ia(c),b=b.ba;for(;e.ba;)a=e.ia(a),e=e.ba;return b===e&&c===a};T.prototype.clone=function(){this.V.X||Ua(this);if(this.V.ha)return this.V.count.value+=1,this;var a=Ya(Object.create(Object.getPrototypeOf(this),{V:{value:Ta(this.V)}}));a.V.count.value+=1;a.V.ga=!1;return a};
T.prototype["delete"]=function(){this.V.X||Ua(this);this.V.ga&&!this.V.ha&&Q("Object already scheduled for deletion");Wa(this);Xa(this.V);this.V.ha||(this.V.$=void 0,this.V.X=void 0)};T.prototype.isDeleted=function(){return!this.V.X};T.prototype.deleteLater=function(){this.V.X||Ua(this);this.V.ga&&!this.V.ha&&Q("Object already scheduled for deletion");$a.push(this);1===$a.length&&Za&&Za(ab);this.V.ga=!0;return this};V.prototype.wa=function(a){this.ra&&(a=this.ra(a));return a};
V.prototype.qa=function(a){this.fa&&this.fa(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=kb;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.la?pb(this.W.da,{Y:this.ya,X:c,aa:this,$:a}):pb(this.W.da,{Y:this,X:a})}var c=this.wa(a);if(!c)return this.qa(a),null;var e=ob(this.W,c);if(void 0!==e){if(0===e.V.count.value)return e.V.X=c,e.V.$=a,e.clone();e=e.clone();this.qa(a);return e}e=this.W.va(c);e=bb[e];if(!e)return b.call(this);e=this.ka?e.sa:e.pointerType;var f=lb(c,this.W,e.W);return null===f?b.call(this):this.la?pb(e.W.da,{Y:e,X:f,aa:this,$:a}):pb(e.W.da,{Y:e,X:f})};
d.getInheritedInstanceCount=function(){return Object.keys(mb).length};d.getLiveInheritedInstances=function(){var a=[],b;for(b in mb)mb.hasOwnProperty(b)&&a.push(mb[b]);return a};d.flushPendingDeletes=ab;d.setDelayFunction=function(a){Za=a;$a.length&&Za&&Za(ab)};rb=d.UnboundTypeError=Qa("UnboundTypeError");d.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Gb={p:function(a){return Fb(a)},o:function(a){"uncaught_exception"in Ka?Ka.pa++:Ka.pa=1;throw a;},t:function(a,b,c,e,f){var g=La(c);b=I(b);S(a,{name:b,fromWireType:function(n){return!!n},toWireType:function(n,h){return h?e:f},argPackAdvance:8,readValueFromPointer:function(n){if(1===c)var h=ta;else if(2===c)h=C;else if(4===c)h=D;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[n>>g])},ca:null})},e:function(a,b,c,e,f,g,n,h,m,k,l,p,r){l=I(l);g=W(f,g);h&&(h=W(n,
h));k&&(k=W(m,k));r=W(p,r);var u=Oa(l);db(u,function(){Y("Cannot construct "+l+" due to unbound types",[e])});R([a,b,c],e?[e]:[],function(t){t=t[0];if(e){var N=t.W;var O=N.da}else O=T.prototype;t=Pa(u,function(){if(Object.getPrototypeOf(this)!==P)throw new M("Use 'new' to construct "+l);if(void 0===J.ea)throw new M(l+" has no accessible constructor");var nb=J.ea[arguments.length];if(void 0===nb)throw new M("Tried to invoke ctor of "+l+" with invalid number of parameters ("+arguments.length+") - expected ("+
Object.keys(J.ea).toString()+") parameters instead!");return nb.apply(this,arguments)});var P=Object.create(O,{constructor:{value:t}});t.prototype=P;var J=new eb(l,t,P,r,N,g,h,k);N=new V(l,J,!0,!1);O=new V(l+"*",J,!1,!1);var ha=new V(l+" const*",J,!1,!0);bb[a]={pointerType:O,sa:ha};qb(u,t);return[N,O,ha]})},c:function(a,b,c,e,f,g){0<b||z("Assertion failed: undefined");var n=ub(b,c);f=W(e,f);var h=[g],m=[];R([],[a],function(k){k=k[0];var l="constructor "+k.name;void 0===k.W.ea&&(k.W.ea=[]);if(void 0!==
k.W.ea[b-1])throw new M("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+k.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");k.W.ea[b-1]=function(){Y("Cannot construct "+k.name+" due to unbound types",n)};R([],n,function(p){k.W.ea[b-1]=function(){arguments.length!==b-1&&Q(l+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;h.length=b;for(var r=1;r<b;++r)h[r]=p[r].toWireType(m,
arguments[r-1]);r=f.apply(null,h);vb(m);return p[0].fromWireType(r)};return[]});return[]})},a:function(a,b,c,e,f,g,n,h){var m=ub(c,e);b=I(b);g=W(f,g);R([],[a],function(k){function l(){Y("Cannot call "+p+" due to unbound types",m)}k=k[0];var p=k.name+"."+b;h&&k.W.za.push(b);var r=k.W.da,u=r[b];void 0===u||void 0===u.Z&&u.className!==k.name&&u.ja===c-2?(l.ja=c-2,l.className=k.name,r[b]=l):(cb(r,b,p),r[b].Z[c-2]=l);R([],m,function(t){t=xb(p,t,k,g,n);void 0===r[b].Z?(t.ja=c-2,r[b]=t):r[b].Z[c-2]=t;return[]});
return[]})},b:function(a,b,c,e,f,g,n,h,m,k){b=I(b);f=W(e,f);R([],[a],function(l){l=l[0];var p=l.name+"."+b,r={get:function(){Y("Cannot access "+p+" due to unbound types",[c,n])},enumerable:!0,configurable:!0};m?r.set=function(){Y("Cannot access "+p+" due to unbound types",[c,n])}:r.set=function(){Q(p+" is a read-only property")};Object.defineProperty(l.W.da,b,r);R([],m?[c,n]:[c],function(u){var t=u[0],N={get:function(){var P=yb(this,l,p+" getter");return t.fromWireType(f(g,P))},enumerable:!0};if(m){m=
W(h,m);var O=u[1];N.set=function(P){var J=yb(this,l,p+" setter"),ha=[];m(k,J,O.toWireType(ha,P));vb(ha)}}Object.defineProperty(l.W.da,b,N);return[]});return[]})},d:function(a,b,c){a=I(a);R([],[b],function(e){e=e[0];d[a]=e.fromWireType(c);return[]})},s:function(a,b){b=I(b);S(a,{name:b,fromWireType:function(c){var e=Z[c].value;Ab(c);return e},toWireType:function(c,e){return ib(e)},argPackAdvance:8,readValueFromPointer:kb,ca:null})},l:function(a,b,c){c=La(c);b=I(b);S(a,{name:b,fromWireType:function(e){return e},
toWireType:function(e,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+U(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Bb(b,c),ca:null})},j:function(a,b,c,e,f,g){var n=ub(b,c);a=I(a);f=W(e,f);db(a,function(){Y("Cannot call "+a+" due to unbound types",n)},b-1);R([],n,function(h){qb(a,xb(a,[h[0],null].concat(h.slice(1)),null,f,g),b-1);return[]})},g:function(a,b,c,e,f){function g(k){return k}b=I(b);-1===f&&(f=4294967295);var n=La(c);if(0===
e){var h=32-8*c;g=function(k){return k<<h>>>h}}var m=-1!=b.indexOf("unsigned");S(a,{name:b,fromWireType:g,toWireType:function(k,l){if("number"!==typeof l&&"boolean"!==typeof l)throw new TypeError('Cannot convert "'+U(l)+'" to '+this.name);if(l<e||l>f)throw new TypeError('Passing a number "'+U(l)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return m?l>>>0:l|0},argPackAdvance:8,readValueFromPointer:Cb(b,n,0!==e),ca:null})},f:function(a,
b,c){function e(g){g>>=2;return new f(sa,E[g+1],E[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=I(c);S(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{xa:!0})},m:function(a,b){b=I(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(e){var f=E[e>>2];if(c)for(var g=e+4,n=0;n<=f;++n){var h=e+4+n;if(n==f||0==B[h]){if(g){var m=g;var k=B,l=m+(h-g);for(g=m;k[g]&&!(g>=l);)++g;if(16<g-m&&k.subarray&&ia)m=ia.decode(k.subarray(m,
g));else{for(l="";m<g;){var p=k[m++];if(p&128){var r=k[m++]&63;if(192==(p&224))l+=String.fromCharCode((p&31)<<6|r);else{var u=k[m++]&63;p=224==(p&240)?(p&15)<<12|r<<6|u:(p&7)<<18|r<<12|u<<6|k[m++]&63;65536>p?l+=String.fromCharCode(p):(p-=65536,l+=String.fromCharCode(55296|p>>10,56320|p&1023))}}else l+=String.fromCharCode(p)}m=l}}else m="";if(void 0===t)var t=m;else t+=String.fromCharCode(0),t+=m;g=h+1}}else{t=Array(f);for(n=0;n<f;++n)t[n]=String.fromCharCode(B[e+4+n]);t=t.join("")}X(e);return t},
toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||Q("Cannot pass non-string to std::string");var n=(c&&g?function(){for(var k=0,l=0;l<f.length;++l){var p=f.charCodeAt(l);55296<=p&&57343>=p&&(p=65536+((p&1023)<<10)|f.charCodeAt(++l)&1023);127>=p?++k:k=2047>=p?k+2:65535>=p?k+3:k+4}return k}:function(){return f.length})(),h=Fb(4+n+1);E[h>>2]=n;if(c&&g)ja(f,h+4,n+1);else if(g)for(g=
0;g<n;++g){var m=f.charCodeAt(g);255<m&&(X(h),Q("String has UTF-16 code units that do not fit in 8 bits"));B[h+4+g]=m}else for(g=0;g<n;++g)B[h+4+g]=f[g];null!==e&&e.push(X,h);return h},argPackAdvance:8,readValueFromPointer:kb,ca:function(e){X(e)}})},i:function(a,b,c){c=I(c);if(2===b){var e=la;var f=na;var g=oa;var n=function(){return ma};var h=1}else 4===b&&(e=pa,f=qa,g=ra,n=function(){return E},h=2);S(a,{name:c,fromWireType:function(m){for(var k=E[m>>2],l=n(),p,r=m+4,u=0;u<=k;++u){var t=m+4+u*b;
if(u==k||0==l[t>>h])r=e(r,t-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=t+b}X(m);return p},toWireType:function(m,k){"string"!==typeof k&&Q("Cannot pass non-string to C++ string type "+c);var l=g(k),p=Fb(4+l+b);E[p>>2]=l>>h;f(k,p+4,l+b);null!==m&&m.push(X,p);return p},argPackAdvance:8,readValueFromPointer:kb,ca:function(m){X(m)}})},u:function(a,b){b=I(b);S(a,{Da:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},v:Ab,n:function(a){4<a&&(Z[a].oa+=1)},h:function(a,
b){var c=L[a];void 0===c&&Q("_emval_take_value has unknown type "+sb(a));a=c.readValueFromPointer(b);return ib(a)},k:function(){z()},q:function(a,b,c){B.copyWithin(a,b,b+c)},r:function(){z("OOM")},memory:A,table:ea};
(function(){function a(f){d.asm=f.exports;G--;d.monitorRunDependencies&&d.monitorRunDependencies(G);0==G&&(null!==Da&&(clearInterval(Da),Da=null),Ea&&(f=Ea,Ea=null,f()))}function b(f){a(f.instance)}function c(f){return Ia().then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){x("failed to asynchronously prepare wasm: "+g);z(g)})}var e={a:Gb};G++;d.monitorRunDependencies&&d.monitorRunDependencies(G);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return x("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(y||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||"function"!==typeof fetch)return c(b);fetch(H,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){x("wasm streaming compile failed: "+g);x("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ja=d.___wasm_call_ctors=function(){return(Ja=d.___wasm_call_ctors=d.asm.w).apply(null,arguments)},Fb=d._malloc=function(){return(Fb=d._malloc=d.asm.x).apply(null,arguments)};d._main=function(){return(d._main=d.asm.y).apply(null,arguments)};var tb=d.___getTypeName=function(){return(tb=d.___getTypeName=d.asm.z).apply(null,arguments)};d.___embind_register_native_and_builtin_types=function(){return(d.___embind_register_native_and_builtin_types=d.asm.A).apply(null,arguments)};
var X=d._free=function(){return(X=d._free=d.asm.B).apply(null,arguments)};d.dynCall_ii=function(){return(d.dynCall_ii=d.asm.C).apply(null,arguments)};d.dynCall_vi=function(){return(d.dynCall_vi=d.asm.D).apply(null,arguments)};d.dynCall_i=function(){return(d.dynCall_i=d.asm.E).apply(null,arguments)};d.dynCall_iiiiii=function(){return(d.dynCall_iiiiii=d.asm.F).apply(null,arguments)};d.dynCall_iiiii=function(){return(d.dynCall_iiiii=d.asm.G).apply(null,arguments)};
d.dynCall_iii=function(){return(d.dynCall_iii=d.asm.H).apply(null,arguments)};d.dynCall_viii=function(){return(d.dynCall_viii=d.asm.I).apply(null,arguments)};d.dynCall_dii=function(){return(d.dynCall_dii=d.asm.J).apply(null,arguments)};d.dynCall_diii=function(){return(d.dynCall_diii=d.asm.K).apply(null,arguments)};d.dynCall_viiii=function(){return(d.dynCall_viiii=d.asm.L).apply(null,arguments)};d.dynCall_vii=function(){return(d.dynCall_vii=d.asm.M).apply(null,arguments)};
d.dynCall_iiii=function(){return(d.dynCall_iiii=d.asm.N).apply(null,arguments)};d.dynCall_viiiii=function(){return(d.dynCall_viiiii=d.asm.O).apply(null,arguments)};d.dynCall_iiddddd=function(){return(d.dynCall_iiddddd=d.asm.P).apply(null,arguments)};d.dynCall_di=function(){return(d.dynCall_di=d.asm.Q).apply(null,arguments)};d.dynCall_viid=function(){return(d.dynCall_viid=d.asm.R).apply(null,arguments)};d.dynCall_iiid=function(){return(d.dynCall_iiid=d.asm.S).apply(null,arguments)};
d.dynCall_iid=function(){return(d.dynCall_iid=d.asm.T).apply(null,arguments)};d.dynCall_viiiiii=function(){return(d.dynCall_viiiiii=d.asm.U).apply(null,arguments)};var Hb;function Ib(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ea=function Jb(){Hb||Kb();Hb||(Ea=Jb)};
function Kb(){function a(){if(!Hb&&(Hb=!0,d.calledRun=!0,!fa)){xa(za);xa(Aa);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Lb){var b=d._main;try{var c=b(0,0);if(!noExitRuntime||0!==c){if(!noExitRuntime&&(fa=!0,d.onExit))d.onExit(c);ca(c,new Ib(c))}}catch(e){e instanceof Ib||("unwind"==e?noExitRuntime=!0:((b=e)&&"object"===typeof e&&e.stack&&(b=[e,e.stack]),x("exception thrown: "+b),ca(1,e)))}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)b=
d.postRun.shift(),Ba.unshift(b);xa(Ba)}}if(!(0<G)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ca();xa(ya);0<G||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}d.run=Kb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Lb=!0;d.noInitialRun&&(Lb=!1);noExitRuntime=!0;Kb();


  return Immolate.ready
}
);
})();
export default Immolate;